// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"03Z_core","status":true,"description":"","parameters":{}},
{"name":"03Z_manager_data","status":false,"description":"","parameters":{}},
{"name":"03Z_manager_images","status":true,"description":"","parameters":{}},
{"name":"03Z_manager_sound","status":true,"description":"","parameters":{}},
{"name":"03Z_manager_scene","status":true,"description":"","parameters":{}},
{"name":"03Z_scene_boot","status":true,"description":"","parameters":{}},
{"name":"03Z_scene_langSelect","status":false,"description":"","parameters":{}},
{"name":"03Z_scene_preload","status":true,"description":"","parameters":{}},
{"name":"SRD_SuperToolsEngine","status":false,"description":"The heart of all maker-style plugins; it adds a playtesting editor that can be opened with F12.","parameters":{"Connect Editor":"true","Auto Open Window":"false","Auto Move Window":"false","Menu Editor Exempt List":"[\"Window_BattleLog\",\"Window_MapName\"]"}},
{"name":"SRD_GameUpgrade","status":false,"description":"Enables more customization over the core mechanics of one's game while also providing additional functions for future plugins.","parameters":{"Game Window":"====================================","Game Reconstruction (1.5.X & below)":"true","Game Resolution":"{\"Width\":\"1280\",\"Height\":\"720\"}","Screen Resolution":"{\"Width\":\"\",\"Height\":\"\"}","Minimum Resolution":"{\"Width\":\"408\",\"Height\":\"312\"}","Maximum Resolution":"{\"Width\":\"\",\"Height\":\"\"}","Window Title":"","Allow Resize":"true","Initial Fullscreen":"false","Show Frame":"true","Always on Top":"false","Core Defaults":"====================================","Audio Master Volume":"100","Video Master Volume":"100","Image Cache Limit":"30","Decrypter Ignore List":"[\"system/Window.png\"]","JsonEx Max Depth":"100","Retry Intervals":"[\"500\",\"1000\",\"3000\"]","HTML Settings":"====================================","Background Color":"#000000","Image Rendering":"auto","PIXI Settings":"====================================","Garbage Collection Mode":"Automatic","Round Pixels":"false","Scale Mode":"Nearest","Wrap Mode":"Clamp"}},
{"name":"SRD_CharacterCreatorEX","status":false,"description":"Allows players to create their own custom characters.","parameters":{"Layers":"Corps, Tenue, Face, Arme2","Order":"Corps, Face, Tenue","Mandatory":"Corps, Face","Mandatory Color":"#FFFF44","Print to Console":"true","== Visual Options ==":"","Use Fade Transition":"true","Use Piece Background":"true","Use Scene Background":"true","Background X Scroll":"1","Background Y Scroll":"0","Small Piece Cols":"3","Big Piece Cols":"1","== Dialogues ==":"","Leave Dialogue":"Confirmer votre personnage ?","Mandatory Dialogue":"Vous devez selectionner un corps.","== Size Options ==":"","Character Width":"96","Character Height":"96","SV Char Width":"128","SV Char Height":"128","Face Width":"144","Face Height":"144"}},
{"name":"SRD_CCEX_DynamicActors","status":false,"description":"Allows Actors to have their images dynamically change based on their class or equipment.","parameters":{}},
{"name":"03Z_SimCraftCore","status":false,"description":"","parameters":{}},
{"name":"03Z_TextManager","status":false,"description":"","parameters":{}},
{"name":"03Z_system_time","status":false,"description":"","parameters":{}},
{"name":"03Z_sprite_timeClock","status":false,"description":"","parameters":{}},
{"name":"03Z_sprite_actorHud","status":false,"description":"","parameters":{}},
{"name":"03Z_system_gather","status":false,"description":"","parameters":{}},
{"name":"03Z_scene_characterSelect","status":false,"description":"","parameters":{}},
{"name":"03Z_scene_worldMap","status":false,"description":"(v1.1) Sistema de mapa de teleporte rápido.","parameters":{"Remember Last MapID":"true","Play Bgm":"false","Bgm File Name":"Theme2","Fade Bgm":"true","Map Move Speed":"30","Center X-axis":"0","Center Y-axis":"0","Fade Speed":"30","Zoom Animation":"true","Rotation Animation":"true","New Map Color":"6","Turn Back After Cancel":"true","List Width":"300","List Height":"290","List X-axis":"516","List Y-axis":"145","Slide List":"true","List Layout X-axis":"0","List Layout Y-axis":"-53","Description X-axis":"160","Description Y-axis":"300","Slide Description":"true","Com Town X-axis":"470","Com Town Y-axis":"7","Com Dungeon X-axis":"575","Com Dungeon Y-axis":"7","Com Other X-axis":"710","Com Other Y-axis":"7","Com Cursor X-axis":"0","Com Cursor Y-axis":"0","Com Cursor Animation":"true","Next Cursor X-axis":"0","Next Cursor Y-axis":"0","Next Cursor Animation":"true","Show Completion":"true","Completion X-axis":"590","Completion Y-axis":"513","Completion Font Size":"22"}}
];
