// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SRD_SuperToolsEngine","status":true,"description":"The heart of all maker-style plugins; it adds a playtesting editor that can be opened with F12.","parameters":{"Connect Editor":"true","Auto Open Window":"false","Auto Move Window":"false","Menu Editor Exempt List":"[\"Window_BattleLog\",\"Window_MapName\"]"}},
{"name":"SRD_GameUpgrade","status":true,"description":"Enables more customization over the core mechanics of one's game while also providing additional functions for future plugins.","parameters":{"Game Window":"====================================","Game Reconstruction (1.5.X & below)":"true","Game Resolution":"{\"Width\":\"1280\",\"Height\":\"720\"}","Screen Resolution":"{\"Width\":\"\",\"Height\":\"\"}","Minimum Resolution":"{\"Width\":\"408\",\"Height\":\"312\"}","Maximum Resolution":"{\"Width\":\"\",\"Height\":\"\"}","Window Title":"","Allow Resize":"true","Initial Fullscreen":"false","Show Frame":"true","Always on Top":"false","Core Defaults":"====================================","Audio Master Volume":"100","Video Master Volume":"100","Image Cache Limit":"30","Decrypter Ignore List":"[\"system/Window.png\"]","JsonEx Max Depth":"100","Retry Intervals":"[\"500\",\"1000\",\"3000\"]","HTML Settings":"====================================","Background Color":"#000000","Image Rendering":"auto","PIXI Settings":"====================================","Garbage Collection Mode":"Automatic","Round Pixels":"false","Scale Mode":"Nearest","Wrap Mode":"Clamp"}},
{"name":"SRD_CharacterCreatorEX","status":true,"description":"Allows players to create their own custom characters.","parameters":{"Layers":"Corps, Tenue, Face, Arme2","Order":"Corps, Face, Tenue","Mandatory":"Corps, Face","Mandatory Color":"#FFFF44","Print to Console":"true","== Visual Options ==":"","Use Fade Transition":"true","Use Piece Background":"true","Use Scene Background":"true","Background X Scroll":"1","Background Y Scroll":"0","Small Piece Cols":"3","Big Piece Cols":"1","== Dialogues ==":"","Leave Dialogue":"Confirmer votre personnage ?","Mandatory Dialogue":"Vous devez selectionner un corps.","== Size Options ==":"","Character Width":"96","Character Height":"96","SV Char Width":"128","SV Char Height":"128","Face Width":"144","Face Height":"144"}},
{"name":"SRD_CCEX_DynamicActors","status":true,"description":"Allows Actors to have their images dynamically change based on their class or equipment.","parameters":{}},
{"name":"03Z_SimCraftCore","status":true,"description":"","parameters":{}},
{"name":"03Z_TextManager","status":true,"description":"","parameters":{}},
{"name":"03Z_system_time","status":true,"description":"","parameters":{}},
{"name":"03Z_sprite_timeClock","status":true,"description":"","parameters":{}},
{"name":"03Z_sprite_actorHud","status":true,"description":"","parameters":{}},
{"name":"03Z_system_gather","status":false,"description":"","parameters":{}},
{"name":"03Z_scene_characterSelect","status":true,"description":"","parameters":{}}
];
